#@TYPE: Machine
#@NAME: Variscite VAR-SOM-AM62P with Secure Boot
#@DESCRIPTION: Machine configuration for the Variscite VAR-SOM-AM62P with Secure Boot
#@MAINTAINER: Matthias Proske <matthias.p@variscite.com>

MACHINEOVERRIDES =. "var-som-secureboot:"
require am62px-var-som.conf

# for Secure Boot, we only support to boot from fitImage
KERNEL_IMAGETYPES = "fitImage"

UBOOT_SIGN_KEYDIR = "${SIGN_KEYDIR}"
UBOOT_SIGN_KEYNAME = "custMpk"
UBOOT_SIGN_ENABLE = "1"

UBOOT_MACHINE = "am62px_var_som_a53_secureboot_prep_defconfig"
