#@TYPE: Machine
#@NAME: VAR-SOM-AM62 (R5F)
#@DESCRIPTION: Machine configuration for the Variscite VAR-SOM-AM62 (R5F core)

require am62x-var-som-k3r5.conf
MACHINEOVERRIDES =. "var-som-secureboot:"

# While all SYSFW_SUFFIX variants are built now in U-Boot by binman, the variables
# here determine which will be packaged for default boot configuration (hs for HS-SE)
SYSFW_SUFFIX = "hs"

UBOOT_MACHINE = "am62x_var_som_r5_secureboot_prep_defconfig"
