#@TYPE: Machine
#@NAME: Variscite VAR-SOM-AM62P
#@DESCRIPTION: Machine configuration for the Variscite VAR-SOM-AM62P EVK
#@MAINTAINER: Francesco Ferraro <francesco.f@variscite.com>

MACHINEOVERRIDES =. "am62pxx:"
require conf/machine/include/am62pxx.inc
require variscite.inc

MACHINE_FEATURES += "bootloader-splash"

KERNEL_DEVICETREE = " \
    ti/k3-am62p5-var-som-symphony.dtb \
"

FIT_CONF_DEFAULT_DTB = "k3-am62p5-var-som-symphony.dtb"

KERNEL_IMAGETYPES = "Image fitImage"

SPL_BINARY = "tispl.bin"
UBOOT_BINARY = "u-boot.img"
UBOOT_SYMLINK = "u-boot.img"
UBOOT_MACHINE = "am62px_var_som_a53_defconfig"

WKS_FILE = "var-sdimage-2part.wks"

# We have to disable SERIAL_CONSOLE due to auto-serial-console
SERIAL_CONSOLES = "115200;ttyS0"

# Enable virtualization
DISTRO_FEATURES:append = " virtualization"

# Remove default TI boot files
IMAGE_BOOT_FILES:remove = " \
    tiboot3-am62px-hs-fs-evm.bin \
    ti_logo_414x97_32bpp.bmp.gz \
"

# and replace with Variscite versions
IMAGE_BOOT_FILES:append = " \
    tiboot3-am62px-hs-fs-${MACHINE}.bin \
"

MACHINE_FEATURES += "nxpiw612-sdio"
